### PR TITLE
group file export actions in the File menu

### PR DESCRIPTION
**Pull request by dxli**
Since we have 3 "File Export" menu entries now, it makes sense to group them in a submenu.

### CODE REVIEW

**Comment by dinkel** [comment]
I like what I see. It makes sense to not clutter the File menu with different "Exports".

Just one question: The "Export to PDF" is copied to the sub-menu, but not removed from the top-level. Is this a glitch or is it on purpose?

**Comment by dxli** [comment]
I removed the duplicate and reordered menu entries a little bit

**Comment by dinkel** [comment]
Thanks, I mergerd the pull request with your enhancements.

Do you think I should open a pull request with this branch towards LibreCAD/LibreCAD?

**Comment by dxli** [comment]
Do you think it's stable enough? If so, we should merge it to the official

**Comment by dinkel** [comment]
I think that stability should not be an issue (however my C++ skills are somewhat limited), but after reflecting a bit, two things should be addressed:
1. The documentation problem on how to "build it on windows" (because of the new library libxml++) should be adressed first.
2. At the moment the splines are not yet converted SVG. As far as I am aware, this is the last drawing primitive missing. I think it would make sens to wait until I have finished this.

Agree?

**Comment by dxli** [comment]
building on win32 shouldn't be a blocker. In my eyes, just requires several hours of hacking.

Spline support would be nice, but the trouble:

spline in LibreCAD itself is kind of messy:

RS_Spline is there, for spline by control points (knots?)
LC_SplinePoints is there, for a 2nd order spline passing given points.

We are talking about better spline support, but no one is actually working on it.

Finally, for coding itself. I will definitely review your additions before merging. As you may noticed, LibreCAD is far from being clean, but we should try our best.

Thanks!

**Comment by dinkel** [comment]
Yes, I saw before, that the spline implementation(s) do not offer all that DXF would allow (i.e. NURBS). 

On the other hand, this is a good thing for me, because SVG can only appriximate NURBS ;-).

For me it is a good thing digging into the spline topic and learning stuff, maybe I could be helping with a more complete (and hopefully cleaner) spline implementation later.

**Comment by dxli** [comment]
For the time being, we export splines as polylines (points created similar to draw() member methods).

Bezier/splines would be very interesting to work on:

For example, basic algorithms are all available:

http://pomax.github.io/bezierinfo/

We should work with Ries to get smooth spline/bezier in LibreCAD.

**Comment by dxli** [comment]
Hi,

I just merged your SVG exporter to master branch.

Thanks!

**Comment by dinkel** [comment]
Cool, thanks!

I've been on internet-free holidays, therefore my delay. What did you think of the code?

It looks as if especially the Windows folks don't like the libxml++ dependency that much https://github.com/LibreCAD/LibreCAD/issues/516 and  https://github.com/LibreCAD/LibreCAD/issues/514 :-(. I can have a look at it and try to use one of the XML writers mentioned in https://github.com/LibreCAD/LibreCAD/issues/516. What do you think?

**Comment by dxli** [comment]
I feel we can figure out libxml++ on win32, just don't have time to do it yet.

**Comment by dxli** [comment]
I didn't realize libxml++ is not not being developed anymore. If so, we'd better switch: boost ptree or QtXML.

I do prefer using of QtXML, so, we don't need another dependency. It's likely we can drop boost usage someday. Currently, we use boost for special math functions (elliptic integral, and linear algebra).

I used boost ptree long time ago.

If it doesn't take long to redo all XML generation, pick one at your convenience.

**Pull request merged**
